# Generated by Django 5.0.14 on 2026-07-08 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyPlayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=100)),
                ('track_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('album_image', models.URLField(blank=True, max_length=500, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('preview_url', models.URLField(blank=True, max_length=500, null=True)),
                ('played_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recently_played', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
        migrations.CreateModel(
            name='LikedAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_album_id', models.CharField(max_length=100)),
                ('album_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_image', models.URLField(blank=True, max_length=500, null=True)),
                ('release_date', models.CharField(blank=True, max_length=50, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'spotify_album_id')},
            },
        ),
        migrations.CreateModel(
            name='LikedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_track_id', models.CharField(max_length=100)),
                ('track_name', models.CharField(max_length=255)),
                ('artist_name', models.CharField(max_length=255)),
                ('album_name', models.CharField(max_length=255)),
                ('album_image', models.URLField(blank=True, max_length=500, null=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('preview_url', models.URLField(blank=True, max_length=500, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_songs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'spotify_track_id')},
            },
        ),
        migrations.CreateModel(
            name='SavedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_artist_id', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=255)),
                ('artist_image', models.URLField(blank=True, max_length=500, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_artists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'spotify_artist_id')},
            },
        ),
    ]
